# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created: Mon Apr 14 10:42:28 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setMargin(3)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabDiagrama = QtGui.QWidget()
        self.tabDiagrama.setObjectName(_fromUtf8("tabDiagrama"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tabDiagrama)
        self.verticalLayout_3.setSpacing(1)
        self.verticalLayout_3.setMargin(1)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.frameEntradas = QtGui.QFrame(self.tabDiagrama)
        self.frameEntradas.setMinimumSize(QtCore.QSize(0, 100))
        self.frameEntradas.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameEntradas.setFrameShadow(QtGui.QFrame.Raised)
        self.frameEntradas.setObjectName(_fromUtf8("frameEntradas"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.frameEntradas)
        self.horizontalLayout_4.setSpacing(4)
        self.horizontalLayout_4.setMargin(1)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.groupBoxRt = QtGui.QGroupBox(self.frameEntradas)
        self.groupBoxRt.setMinimumSize(QtCore.QSize(220, 0))
        self.groupBoxRt.setMaximumSize(QtCore.QSize(250, 16777215))
        self.groupBoxRt.setObjectName(_fromUtf8("groupBoxRt"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBoxRt)
        self.gridLayout_4.setMargin(4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.labelRvalue = QtGui.QLabel(self.groupBoxRt)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelRvalue.sizePolicy().hasHeightForWidth())
        self.labelRvalue.setSizePolicy(sizePolicy)
        self.labelRvalue.setMinimumSize(QtCore.QSize(70, 0))
        self.labelRvalue.setMaximumSize(QtCore.QSize(70, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelRvalue.setFont(font)
        self.labelRvalue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelRvalue.setObjectName(_fromUtf8("labelRvalue"))
        self.gridLayout_4.addWidget(self.labelRvalue, 0, 0, 1, 1)
        self.lineEditRvalue = QtGui.QLineEdit(self.groupBoxRt)
        self.lineEditRvalue.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEditRvalue.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditRvalue.setFont(font)
        self.lineEditRvalue.setText(_fromUtf8("1"))
        self.lineEditRvalue.setObjectName(_fromUtf8("lineEditRvalue"))
        self.gridLayout_4.addWidget(self.lineEditRvalue, 0, 1, 1, 1)
        self.labelRtime = QtGui.QLabel(self.groupBoxRt)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelRtime.sizePolicy().hasHeightForWidth())
        self.labelRtime.setSizePolicy(sizePolicy)
        self.labelRtime.setMinimumSize(QtCore.QSize(70, 0))
        self.labelRtime.setMaximumSize(QtCore.QSize(70, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelRtime.setFont(font)
        self.labelRtime.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelRtime.setObjectName(_fromUtf8("labelRtime"))
        self.gridLayout_4.addWidget(self.labelRtime, 1, 0, 1, 1)
        self.doubleSpinBoxRtime = QtGui.QDoubleSpinBox(self.groupBoxRt)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxRtime.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxRtime.setSizePolicy(sizePolicy)
        self.doubleSpinBoxRtime.setMinimumSize(QtCore.QSize(0, 25))
        self.doubleSpinBoxRtime.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.doubleSpinBoxRtime.setFont(font)
        self.doubleSpinBoxRtime.setMinimum(0.0)
        self.doubleSpinBoxRtime.setMaximum(2000.0)
        self.doubleSpinBoxRtime.setProperty("value", 0.0)
        self.doubleSpinBoxRtime.setObjectName(_fromUtf8("doubleSpinBoxRtime"))
        self.gridLayout_4.addWidget(self.doubleSpinBoxRtime, 1, 1, 1, 1)
        self.horizontalLayout_4.addWidget(self.groupBoxRt)
        self.groupBoxWt = QtGui.QGroupBox(self.frameEntradas)
        self.groupBoxWt.setMinimumSize(QtCore.QSize(220, 0))
        self.groupBoxWt.setMaximumSize(QtCore.QSize(250, 16777215))
        self.groupBoxWt.setCheckable(True)
        self.groupBoxWt.setObjectName(_fromUtf8("groupBoxWt"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBoxWt)
        self.gridLayout_5.setMargin(4)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.labelWvalue = QtGui.QLabel(self.groupBoxWt)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelWvalue.sizePolicy().hasHeightForWidth())
        self.labelWvalue.setSizePolicy(sizePolicy)
        self.labelWvalue.setMinimumSize(QtCore.QSize(70, 0))
        self.labelWvalue.setMaximumSize(QtCore.QSize(70, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelWvalue.setFont(font)
        self.labelWvalue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelWvalue.setObjectName(_fromUtf8("labelWvalue"))
        self.gridLayout_5.addWidget(self.labelWvalue, 0, 0, 1, 1)
        self.lineEditWvalue = QtGui.QLineEdit(self.groupBoxWt)
        self.lineEditWvalue.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEditWvalue.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditWvalue.setFont(font)
        self.lineEditWvalue.setText(_fromUtf8("1"))
        self.lineEditWvalue.setObjectName(_fromUtf8("lineEditWvalue"))
        self.gridLayout_5.addWidget(self.lineEditWvalue, 0, 1, 1, 1)
        self.labelWtime = QtGui.QLabel(self.groupBoxWt)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelWtime.sizePolicy().hasHeightForWidth())
        self.labelWtime.setSizePolicy(sizePolicy)
        self.labelWtime.setMinimumSize(QtCore.QSize(70, 0))
        self.labelWtime.setMaximumSize(QtCore.QSize(70, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelWtime.setFont(font)
        self.labelWtime.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelWtime.setObjectName(_fromUtf8("labelWtime"))
        self.gridLayout_5.addWidget(self.labelWtime, 1, 0, 1, 1)
        self.doubleSpinBoxWtime = QtGui.QDoubleSpinBox(self.groupBoxWt)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxWtime.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxWtime.setSizePolicy(sizePolicy)
        self.doubleSpinBoxWtime.setMinimumSize(QtCore.QSize(0, 25))
        self.doubleSpinBoxWtime.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.doubleSpinBoxWtime.setFont(font)
        self.doubleSpinBoxWtime.setMinimum(0.0)
        self.doubleSpinBoxWtime.setMaximum(2000.0)
        self.doubleSpinBoxWtime.setProperty("value", 0.0)
        self.doubleSpinBoxWtime.setObjectName(_fromUtf8("doubleSpinBoxWtime"))
        self.gridLayout_5.addWidget(self.doubleSpinBoxWtime, 1, 1, 1, 1)
        self.horizontalLayout_4.addWidget(self.groupBoxWt)
        spacerItem = QtGui.QSpacerItem(98, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.comboBoxSys = QtGui.QComboBox(self.frameEntradas)
        self.comboBoxSys.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.comboBoxSys.setObjectName(_fromUtf8("comboBoxSys"))
        self.comboBoxSys.addItem(_fromUtf8(""))
        self.comboBoxSys.addItem(_fromUtf8(""))
        self.comboBoxSys.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.comboBoxSys)
        self.verticalLayout_3.addWidget(self.frameEntradas)
        self.graphicsView = QtGui.QGraphicsView(self.tabDiagrama)
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.verticalLayout_3.addWidget(self.graphicsView)
        self.frameSis = QtGui.QFrame(self.tabDiagrama)
        self.frameSis.setMinimumSize(QtCore.QSize(0, 100))
        self.frameSis.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameSis.setFrameShadow(QtGui.QFrame.Raised)
        self.frameSis.setObjectName(_fromUtf8("frameSis"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frameSis)
        self.horizontalLayout.setMargin(1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.groupBoxMalha = QtGui.QGroupBox(self.frameSis)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBoxMalha.setFont(font)
        self.groupBoxMalha.setObjectName(_fromUtf8("groupBoxMalha"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBoxMalha)
        self.verticalLayout_4.setContentsMargins(4, 2, 4, 4)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.radioBtnOpen = QtGui.QRadioButton(self.groupBoxMalha)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioBtnOpen.setFont(font)
        self.radioBtnOpen.setChecked(True)
        self.radioBtnOpen.setAutoExclusive(True)
        self.radioBtnOpen.setObjectName(_fromUtf8("radioBtnOpen"))
        self.verticalLayout_4.addWidget(self.radioBtnOpen)
        self.radioBtnClose = QtGui.QRadioButton(self.groupBoxMalha)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioBtnClose.setFont(font)
        self.radioBtnClose.setObjectName(_fromUtf8("radioBtnClose"))
        self.verticalLayout_4.addWidget(self.radioBtnClose)
        self.horizontalLayout.addWidget(self.groupBoxMalha)
        self.groupBoxK = QtGui.QGroupBox(self.frameSis)
        self.groupBoxK.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBoxK.setFont(font)
        self.groupBoxK.setStyleSheet(_fromUtf8("QGroupBox {border-width: 2px; border-style: solid;\n"
"border-color: rgb(255, 170, 170);\n"
"border-radius: 5px;}\n"
"QGroupBox::title {\n"
"     background-color: transparent;\n"
"     subcontrol-origin: border;\n"
"     subcontrol-position: top left; /* position at the top center */\n"
"     padding: 0 10px;\n"
" }"))
        self.groupBoxK.setObjectName(_fromUtf8("groupBoxK"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBoxK)
        self.verticalLayout_5.setContentsMargins(1, 4, 1, 4)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.labelK = QtGui.QLabel(self.groupBoxK)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelK.sizePolicy().hasHeightForWidth())
        self.labelK.setSizePolicy(sizePolicy)
        self.labelK.setMinimumSize(QtCore.QSize(0, 20))
        self.labelK.setMaximumSize(QtCore.QSize(200, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelK.setFont(font)
        self.labelK.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelK.setText(_fromUtf8("K:"))
        self.labelK.setAlignment(QtCore.Qt.AlignCenter)
        self.labelK.setObjectName(_fromUtf8("labelK"))
        self.verticalLayout_5.addWidget(self.labelK)
        self.doubleSpinBoxK = QtGui.QDoubleSpinBox(self.groupBoxK)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxK.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxK.setSizePolicy(sizePolicy)
        self.doubleSpinBoxK.setMinimumSize(QtCore.QSize(0, 25))
        self.doubleSpinBoxK.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.doubleSpinBoxK.setFont(font)
        self.doubleSpinBoxK.setMinimum(-200.0)
        self.doubleSpinBoxK.setMaximum(200.0)
        self.doubleSpinBoxK.setProperty("value", 1.0)
        self.doubleSpinBoxK.setObjectName(_fromUtf8("doubleSpinBoxK"))
        self.verticalLayout_5.addWidget(self.doubleSpinBoxK)
        self.horizontalLayout.addWidget(self.groupBoxK)
        self.groupBoxC = QtGui.QGroupBox(self.frameSis)
        self.groupBoxC.setEnabled(True)
        self.groupBoxC.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBoxC.setFont(font)
        self.groupBoxC.setStyleSheet(_fromUtf8("QGroupBox {border-width: 2px; border-style: solid;\n"
"border-color: rgb(175, 198, 233);\n"
"border-radius: 5px;}\n"
"QGroupBox::title {\n"
"     background-color: transparent;\n"
"     subcontrol-origin: border;\n"
"     subcontrol-position: top left; /* position at the top center */\n"
"     padding: 0 10px;\n"
" }"))
        self.groupBoxC.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBoxC.setCheckable(True)
        self.groupBoxC.setChecked(False)
        self.groupBoxC.setObjectName(_fromUtf8("groupBoxC"))
        self.gridLayout = QtGui.QGridLayout(self.groupBoxC)
        self.gridLayout.setContentsMargins(4, 4, 4, 0)
        self.gridLayout.setVerticalSpacing(1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.labelCnum = QtGui.QLabel(self.groupBoxC)
        self.labelCnum.setMinimumSize(QtCore.QSize(40, 0))
        self.labelCnum.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelCnum.setFont(font)
        self.labelCnum.setObjectName(_fromUtf8("labelCnum"))
        self.gridLayout.addWidget(self.labelCnum, 0, 0, 1, 1)
        self.lineEditCnum = QtGui.QLineEdit(self.groupBoxC)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditCnum.sizePolicy().hasHeightForWidth())
        self.lineEditCnum.setSizePolicy(sizePolicy)
        self.lineEditCnum.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEditCnum.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditCnum.setFont(font)
        self.lineEditCnum.setText(_fromUtf8("1"))
        self.lineEditCnum.setObjectName(_fromUtf8("lineEditCnum"))
        self.gridLayout.addWidget(self.lineEditCnum, 0, 1, 1, 1)
        self.labelCden = QtGui.QLabel(self.groupBoxC)
        self.labelCden.setMinimumSize(QtCore.QSize(40, 0))
        self.labelCden.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelCden.setFont(font)
        self.labelCden.setObjectName(_fromUtf8("labelCden"))
        self.gridLayout.addWidget(self.labelCden, 1, 0, 1, 1)
        self.lineEditCden = QtGui.QLineEdit(self.groupBoxC)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditCden.sizePolicy().hasHeightForWidth())
        self.lineEditCden.setSizePolicy(sizePolicy)
        self.lineEditCden.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEditCden.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditCden.setFont(font)
        self.lineEditCden.setText(_fromUtf8("1"))
        self.lineEditCden.setObjectName(_fromUtf8("lineEditCden"))
        self.gridLayout.addWidget(self.lineEditCden, 1, 1, 1, 1)
        self.horizontalLayout.addWidget(self.groupBoxC)
        self.groupBoxG = QtGui.QGroupBox(self.frameSis)
        self.groupBoxG.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBoxG.setFont(font)
        self.groupBoxG.setStyleSheet(_fromUtf8("QGroupBox {border-width: 2px; border-style: solid;\n"
"border-color: rgb(95, 211, 141);\n"
"border-radius: 5px;}\n"
"QGroupBox::title {\n"
"     background-color: transparent;\n"
"     subcontrol-origin: border;\n"
"     subcontrol-position: top left; /* position at the top center */\n"
"     padding: 0 10px;\n"
" }"))
        self.groupBoxG.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBoxG.setCheckable(True)
        self.groupBoxG.setObjectName(_fromUtf8("groupBoxG"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBoxG)
        self.gridLayout_2.setContentsMargins(4, 4, 4, 0)
        self.gridLayout_2.setVerticalSpacing(1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.labelGnum = QtGui.QLabel(self.groupBoxG)
        self.labelGnum.setMinimumSize(QtCore.QSize(40, 0))
        self.labelGnum.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelGnum.setFont(font)
        self.labelGnum.setText(_fromUtf8("Num:"))
        self.labelGnum.setObjectName(_fromUtf8("labelGnum"))
        self.gridLayout_2.addWidget(self.labelGnum, 0, 0, 1, 1)
        self.lineEditGnum = QtGui.QLineEdit(self.groupBoxG)
        self.lineEditGnum.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEditGnum.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditGnum.setFont(font)
        self.lineEditGnum.setText(_fromUtf8("2*s+10"))
        self.lineEditGnum.setObjectName(_fromUtf8("lineEditGnum"))
        self.gridLayout_2.addWidget(self.lineEditGnum, 0, 1, 1, 1)
        self.labelGden = QtGui.QLabel(self.groupBoxG)
        self.labelGden.setMinimumSize(QtCore.QSize(40, 0))
        self.labelGden.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelGden.setFont(font)
        self.labelGden.setText(_fromUtf8("Den:"))
        self.labelGden.setObjectName(_fromUtf8("labelGden"))
        self.gridLayout_2.addWidget(self.labelGden, 1, 0, 1, 1)
        self.lineEditGden = QtGui.QLineEdit(self.groupBoxG)
        self.lineEditGden.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEditGden.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditGden.setFont(font)
        self.lineEditGden.setText(_fromUtf8("1*s^2+2*s+10"))
        self.lineEditGden.setObjectName(_fromUtf8("lineEditGden"))
        self.gridLayout_2.addWidget(self.lineEditGden, 1, 1, 1, 1)
        self.horizontalLayout.addWidget(self.groupBoxG)
        self.groupBoxH = QtGui.QGroupBox(self.frameSis)
        self.groupBoxH.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBoxH.setFont(font)
        self.groupBoxH.setStyleSheet(_fromUtf8("QGroupBox {border-width: 2px; border-style: solid;\n"
"border-color: rgb(255, 246, 136);\n"
"border-radius: 5px;}\n"
"QGroupBox::title {\n"
"     background-color: transparent;\n"
"     subcontrol-origin: border;\n"
"     subcontrol-position: top left; /* position at the top center */\n"
"     padding: 0 10px;\n"
" }"))
        self.groupBoxH.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBoxH.setCheckable(True)
        self.groupBoxH.setChecked(False)
        self.groupBoxH.setObjectName(_fromUtf8("groupBoxH"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBoxH)
        self.gridLayout_3.setContentsMargins(4, 4, 4, 0)
        self.gridLayout_3.setVerticalSpacing(1)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.labelHnum = QtGui.QLabel(self.groupBoxH)
        self.labelHnum.setMinimumSize(QtCore.QSize(40, 0))
        self.labelHnum.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelHnum.setFont(font)
        self.labelHnum.setText(_fromUtf8("Num:"))
        self.labelHnum.setObjectName(_fromUtf8("labelHnum"))
        self.gridLayout_3.addWidget(self.labelHnum, 0, 0, 1, 1)
        self.lineEditHnum = QtGui.QLineEdit(self.groupBoxH)
        self.lineEditHnum.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEditHnum.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditHnum.setFont(font)
        self.lineEditHnum.setText(_fromUtf8("1"))
        self.lineEditHnum.setObjectName(_fromUtf8("lineEditHnum"))
        self.gridLayout_3.addWidget(self.lineEditHnum, 0, 1, 1, 1)
        self.labelHden = QtGui.QLabel(self.groupBoxH)
        self.labelHden.setMinimumSize(QtCore.QSize(40, 0))
        self.labelHden.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelHden.setFont(font)
        self.labelHden.setText(_fromUtf8("Den:"))
        self.labelHden.setObjectName(_fromUtf8("labelHden"))
        self.gridLayout_3.addWidget(self.labelHden, 1, 0, 1, 1)
        self.lineEditHden = QtGui.QLineEdit(self.groupBoxH)
        self.lineEditHden.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEditHden.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditHden.setFont(font)
        self.lineEditHden.setText(_fromUtf8("1"))
        self.lineEditHden.setObjectName(_fromUtf8("lineEditHden"))
        self.gridLayout_3.addWidget(self.lineEditHden, 1, 1, 1, 1)
        self.horizontalLayout.addWidget(self.groupBoxH)
        self.verticalLayout_3.addWidget(self.frameSis)
        self.tabWidget.addTab(self.tabDiagrama, _fromUtf8(""))
        self.tabSimul = QtGui.QWidget()
        self.tabSimul.setObjectName(_fromUtf8("tabSimul"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tabSimul)
        self.horizontalLayout_2.setMargin(4)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.frameSimul = QtGui.QFrame(self.tabSimul)
        self.frameSimul.setMinimumSize(QtCore.QSize(160, 0))
        self.frameSimul.setMaximumSize(QtCore.QSize(160, 16777215))
        self.frameSimul.setAutoFillBackground(False)
        self.frameSimul.setFrameShape(QtGui.QFrame.Box)
        self.frameSimul.setFrameShadow(QtGui.QFrame.Sunken)
        self.frameSimul.setLineWidth(1)
        self.frameSimul.setMidLineWidth(0)
        self.frameSimul.setObjectName(_fromUtf8("frameSimul"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frameSimul)
        self.verticalLayout_2.setMargin(4)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.labelSimulTit = QtGui.QLabel(self.frameSimul)
        self.labelSimulTit.setMinimumSize(QtCore.QSize(0, 20))
        self.labelSimulTit.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelSimulTit.setFont(font)
        self.labelSimulTit.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSimulTit.setObjectName(_fromUtf8("labelSimulTit"))
        self.verticalLayout_2.addWidget(self.labelSimulTit)
        self.labelTmax = QtGui.QLabel(self.frameSimul)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelTmax.setFont(font)
        self.labelTmax.setText(_fromUtf8("Tmax [s]:"))
        self.labelTmax.setObjectName(_fromUtf8("labelTmax"))
        self.verticalLayout_2.addWidget(self.labelTmax)
        self.doubleSpinBoxTmax = QtGui.QDoubleSpinBox(self.frameSimul)
        self.doubleSpinBoxTmax.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.doubleSpinBoxTmax.setFont(font)
        self.doubleSpinBoxTmax.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBoxTmax.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.doubleSpinBoxTmax.setDecimals(1)
        self.doubleSpinBoxTmax.setMaximum(2000.0)
        self.doubleSpinBoxTmax.setProperty("value", 10.0)
        self.doubleSpinBoxTmax.setObjectName(_fromUtf8("doubleSpinBoxTmax"))
        self.verticalLayout_2.addWidget(self.doubleSpinBoxTmax)
        spacerItem1 = QtGui.QSpacerItem(20, 60, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.labelMostrar = QtGui.QLabel(self.frameSimul)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelMostrar.setFont(font)
        self.labelMostrar.setObjectName(_fromUtf8("labelMostrar"))
        self.verticalLayout_2.addWidget(self.labelMostrar)
        self.checkBoxSaida = QtGui.QCheckBox(self.frameSimul)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.checkBoxSaida.setFont(font)
        self.checkBoxSaida.setChecked(True)
        self.checkBoxSaida.setObjectName(_fromUtf8("checkBoxSaida"))
        self.verticalLayout_2.addWidget(self.checkBoxSaida)
        self.checkBoxEntrada = QtGui.QCheckBox(self.frameSimul)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBoxEntrada.setFont(font)
        self.checkBoxEntrada.setChecked(True)
        self.checkBoxEntrada.setObjectName(_fromUtf8("checkBoxEntrada"))
        self.verticalLayout_2.addWidget(self.checkBoxEntrada)
        self.checkBoxErro = QtGui.QCheckBox(self.frameSimul)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBoxErro.setFont(font)
        self.checkBoxErro.setObjectName(_fromUtf8("checkBoxErro"))
        self.verticalLayout_2.addWidget(self.checkBoxErro)
        self.checkBoxControle = QtGui.QCheckBox(self.frameSimul)
        self.checkBoxControle.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBoxControle.setFont(font)
        self.checkBoxControle.setObjectName(_fromUtf8("checkBoxControle"))
        self.verticalLayout_2.addWidget(self.checkBoxControle)
        self.checkBoxPert = QtGui.QCheckBox(self.frameSimul)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBoxPert.setFont(font)
        self.checkBoxPert.setObjectName(_fromUtf8("checkBoxPert"))
        self.verticalLayout_2.addWidget(self.checkBoxPert)
        spacerItem2 = QtGui.QSpacerItem(20, 61, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.btnSimul = QtGui.QPushButton(self.frameSimul)
        self.btnSimul.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnSimul.setFont(font)
        self.btnSimul.setObjectName(_fromUtf8("btnSimul"))
        self.verticalLayout_2.addWidget(self.btnSimul)
        self.btnContinuar = QtGui.QPushButton(self.frameSimul)
        self.btnContinuar.setEnabled(False)
        self.btnContinuar.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnContinuar.setFont(font)
        self.btnContinuar.setObjectName(_fromUtf8("btnContinuar"))
        self.verticalLayout_2.addWidget(self.btnContinuar)
        self.btnLimparSimul = QtGui.QPushButton(self.frameSimul)
        self.btnLimparSimul.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnLimparSimul.setFont(font)
        self.btnLimparSimul.setObjectName(_fromUtf8("btnLimparSimul"))
        self.verticalLayout_2.addWidget(self.btnLimparSimul)
        self.horizontalLayout_2.addWidget(self.frameSimul)
        self.VBoxLayoutSimul = QtGui.QVBoxLayout()
        self.VBoxLayoutSimul.setObjectName(_fromUtf8("VBoxLayoutSimul"))
        self.mplSimul = MatplotlibWidget(self.tabSimul)
        self.mplSimul.setObjectName(_fromUtf8("mplSimul"))
        self.VBoxLayoutSimul.addWidget(self.mplSimul)
        self.horizontalLayout_2.addLayout(self.VBoxLayoutSimul)
        self.tabWidget.addTab(self.tabSimul, _fromUtf8(""))
        self.tabLGR = QtGui.QWidget()
        self.tabLGR.setObjectName(_fromUtf8("tabLGR"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.tabLGR)
        self.horizontalLayout_3.setMargin(4)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.frameLGR = QtGui.QFrame(self.tabLGR)
        self.frameLGR.setMinimumSize(QtCore.QSize(160, 0))
        self.frameLGR.setMaximumSize(QtCore.QSize(160, 16777215))
        self.frameLGR.setFrameShape(QtGui.QFrame.Box)
        self.frameLGR.setFrameShadow(QtGui.QFrame.Sunken)
        self.frameLGR.setObjectName(_fromUtf8("frameLGR"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.frameLGR)
        self.verticalLayout_6.setMargin(4)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.labelLGRTit = QtGui.QLabel(self.frameLGR)
        self.labelLGRTit.setMinimumSize(QtCore.QSize(0, 20))
        self.labelLGRTit.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelLGRTit.setFont(font)
        self.labelLGRTit.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLGRTit.setObjectName(_fromUtf8("labelLGRTit"))
        self.verticalLayout_6.addWidget(self.labelLGRTit)
        self.frameLGR1 = QtGui.QFrame(self.frameLGR)
        self.frameLGR1.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameLGR1.setFrameShadow(QtGui.QFrame.Raised)
        self.frameLGR1.setObjectName(_fromUtf8("frameLGR1"))
        self.gridLayout_6 = QtGui.QGridLayout(self.frameLGR1)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.labelKmax = QtGui.QLabel(self.frameLGR1)
        self.labelKmax.setMinimumSize(QtCore.QSize(0, 20))
        self.labelKmax.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelKmax.setFont(font)
        self.labelKmax.setText(_fromUtf8("Kmax:"))
        self.labelKmax.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelKmax.setObjectName(_fromUtf8("labelKmax"))
        self.gridLayout_6.addWidget(self.labelKmax, 0, 0, 1, 1)
        self.doubleSpinBoxKmax = QtGui.QDoubleSpinBox(self.frameLGR1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxKmax.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxKmax.setSizePolicy(sizePolicy)
        self.doubleSpinBoxKmax.setMinimumSize(QtCore.QSize(0, 25))
        self.doubleSpinBoxKmax.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.doubleSpinBoxKmax.setFont(font)
        self.doubleSpinBoxKmax.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBoxKmax.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.doubleSpinBoxKmax.setDecimals(1)
        self.doubleSpinBoxKmax.setMinimum(1.0)
        self.doubleSpinBoxKmax.setMaximum(2000.0)
        self.doubleSpinBoxKmax.setProperty("value", 10.0)
        self.doubleSpinBoxKmax.setObjectName(_fromUtf8("doubleSpinBoxKmax"))
        self.gridLayout_6.addWidget(self.doubleSpinBoxKmax, 0, 1, 1, 2)
        self.labelKmin = QtGui.QLabel(self.frameLGR1)
        self.labelKmin.setMinimumSize(QtCore.QSize(0, 20))
        self.labelKmin.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelKmin.setFont(font)
        self.labelKmin.setText(_fromUtf8("Kmin:"))
        self.labelKmin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelKmin.setObjectName(_fromUtf8("labelKmin"))
        self.gridLayout_6.addWidget(self.labelKmin, 1, 0, 1, 1)
        self.doubleSpinBoxKmin = QtGui.QDoubleSpinBox(self.frameLGR1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxKmin.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxKmin.setSizePolicy(sizePolicy)
        self.doubleSpinBoxKmin.setMinimumSize(QtCore.QSize(0, 25))
        self.doubleSpinBoxKmin.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.doubleSpinBoxKmin.setFont(font)
        self.doubleSpinBoxKmin.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBoxKmin.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.doubleSpinBoxKmin.setDecimals(1)
        self.doubleSpinBoxKmin.setMaximum(2000.0)
        self.doubleSpinBoxKmin.setProperty("value", 0.0)
        self.doubleSpinBoxKmin.setObjectName(_fromUtf8("doubleSpinBoxKmin"))
        self.gridLayout_6.addWidget(self.doubleSpinBoxKmin, 1, 1, 1, 2)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem3)
        self.labelKlgr = QtGui.QLabel(self.frameLGR1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelKlgr.sizePolicy().hasHeightForWidth())
        self.labelKlgr.setSizePolicy(sizePolicy)
        self.labelKlgr.setMinimumSize(QtCore.QSize(0, 20))
        self.labelKlgr.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelKlgr.setFont(font)
        self.labelKlgr.setText(_fromUtf8("Ganho K:"))
        self.labelKlgr.setAlignment(QtCore.Qt.AlignCenter)
        self.labelKlgr.setObjectName(_fromUtf8("labelKlgr"))
        self.verticalLayout_7.addWidget(self.labelKlgr)
        self.doubleSpinBoxKlgr = QtGui.QDoubleSpinBox(self.frameLGR1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxKlgr.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxKlgr.setSizePolicy(sizePolicy)
        self.doubleSpinBoxKlgr.setMinimumSize(QtCore.QSize(0, 25))
        self.doubleSpinBoxKlgr.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.doubleSpinBoxKlgr.setFont(font)
        self.doubleSpinBoxKlgr.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBoxKlgr.setMinimum(-200.0)
        self.doubleSpinBoxKlgr.setMaximum(200.0)
        self.doubleSpinBoxKlgr.setProperty("value", 1.0)
        self.doubleSpinBoxKlgr.setObjectName(_fromUtf8("doubleSpinBoxKlgr"))
        self.verticalLayout_7.addWidget(self.doubleSpinBoxKlgr)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem4)
        self.gridLayout_6.addLayout(self.verticalLayout_7, 2, 0, 1, 2)
        self.verticalSliderK = QtGui.QSlider(self.frameLGR1)
        self.verticalSliderK.setMinimumSize(QtCore.QSize(40, 0))
        self.verticalSliderK.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.verticalSliderK.setFont(font)
        self.verticalSliderK.setMaximum(200)
        self.verticalSliderK.setProperty("value", 20)
        self.verticalSliderK.setSliderPosition(20)
        self.verticalSliderK.setOrientation(QtCore.Qt.Vertical)
        self.verticalSliderK.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.verticalSliderK.setObjectName(_fromUtf8("verticalSliderK"))
        self.gridLayout_6.addWidget(self.verticalSliderK, 2, 2, 1, 1)
        self.labelRebd = QtGui.QLabel(self.frameLGR1)
        self.labelRebd.setMinimumSize(QtCore.QSize(0, 20))
        self.labelRebd.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelRebd.setFont(font)
        self.labelRebd.setText(_fromUtf8("Rebd:"))
        self.labelRebd.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelRebd.setObjectName(_fromUtf8("labelRebd"))
        self.gridLayout_6.addWidget(self.labelRebd, 3, 0, 1, 1)
        self.doubleSpinBoxRebd = QtGui.QDoubleSpinBox(self.frameLGR1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxRebd.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxRebd.setSizePolicy(sizePolicy)
        self.doubleSpinBoxRebd.setMinimumSize(QtCore.QSize(0, 25))
        self.doubleSpinBoxRebd.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.doubleSpinBoxRebd.setFont(font)
        self.doubleSpinBoxRebd.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBoxRebd.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.doubleSpinBoxRebd.setDecimals(2)
        self.doubleSpinBoxRebd.setMinimum(-1000.0)
        self.doubleSpinBoxRebd.setMaximum(1000.0)
        self.doubleSpinBoxRebd.setSingleStep(0.5)
        self.doubleSpinBoxRebd.setProperty("value", 0.0)
        self.doubleSpinBoxRebd.setObjectName(_fromUtf8("doubleSpinBoxRebd"))
        self.gridLayout_6.addWidget(self.doubleSpinBoxRebd, 3, 1, 1, 2)
        self.labelRibd = QtGui.QLabel(self.frameLGR1)
        self.labelRibd.setMinimumSize(QtCore.QSize(0, 20))
        self.labelRibd.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelRibd.setFont(font)
        self.labelRibd.setText(_fromUtf8("Ribd:"))
        self.labelRibd.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelRibd.setObjectName(_fromUtf8("labelRibd"))
        self.gridLayout_6.addWidget(self.labelRibd, 4, 0, 1, 1)
        self.doubleSpinBoxRibd = QtGui.QDoubleSpinBox(self.frameLGR1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxRibd.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxRibd.setSizePolicy(sizePolicy)
        self.doubleSpinBoxRibd.setMinimumSize(QtCore.QSize(0, 25))
        self.doubleSpinBoxRibd.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.doubleSpinBoxRibd.setFont(font)
        self.doubleSpinBoxRibd.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBoxRibd.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.doubleSpinBoxRibd.setDecimals(2)
        self.doubleSpinBoxRibd.setMinimum(-1000.0)
        self.doubleSpinBoxRibd.setMaximum(1000.0)
        self.doubleSpinBoxRibd.setSingleStep(0.5)
        self.doubleSpinBoxRibd.setProperty("value", 0.0)
        self.doubleSpinBoxRibd.setObjectName(_fromUtf8("doubleSpinBoxRibd"))
        self.gridLayout_6.addWidget(self.doubleSpinBoxRibd, 4, 1, 1, 2)
        self.labelImbd = QtGui.QLabel(self.frameLGR1)
        self.labelImbd.setMinimumSize(QtCore.QSize(0, 20))
        self.labelImbd.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelImbd.setFont(font)
        self.labelImbd.setText(_fromUtf8("Imbd:"))
        self.labelImbd.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelImbd.setObjectName(_fromUtf8("labelImbd"))
        self.gridLayout_6.addWidget(self.labelImbd, 5, 0, 1, 1)
        self.doubleSpinBoxImbd = QtGui.QDoubleSpinBox(self.frameLGR1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxImbd.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxImbd.setSizePolicy(sizePolicy)
        self.doubleSpinBoxImbd.setMinimumSize(QtCore.QSize(0, 25))
        self.doubleSpinBoxImbd.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.doubleSpinBoxImbd.setFont(font)
        self.doubleSpinBoxImbd.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBoxImbd.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.doubleSpinBoxImbd.setDecimals(2)
        self.doubleSpinBoxImbd.setMinimum(-1000.0)
        self.doubleSpinBoxImbd.setMaximum(1000.0)
        self.doubleSpinBoxImbd.setSingleStep(0.5)
        self.doubleSpinBoxImbd.setProperty("value", 0.0)
        self.doubleSpinBoxImbd.setObjectName(_fromUtf8("doubleSpinBoxImbd"))
        self.gridLayout_6.addWidget(self.doubleSpinBoxImbd, 5, 1, 1, 2)
        self.verticalLayout_6.addWidget(self.frameLGR1)
        self.btnPlotLGR = QtGui.QPushButton(self.frameLGR)
        self.btnPlotLGR.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnPlotLGR.setFont(font)
        self.btnPlotLGR.setObjectName(_fromUtf8("btnPlotLGR"))
        self.verticalLayout_6.addWidget(self.btnPlotLGR)
        self.btnPlotLGRcomp = QtGui.QPushButton(self.frameLGR)
        self.btnPlotLGRcomp.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnPlotLGRcomp.setFont(font)
        self.btnPlotLGRcomp.setObjectName(_fromUtf8("btnPlotLGRcomp"))
        self.verticalLayout_6.addWidget(self.btnPlotLGRcomp)
        self.horizontalLayout_3.addWidget(self.frameLGR)
        self.VBoxLayoutLGR = QtGui.QVBoxLayout()
        self.VBoxLayoutLGR.setObjectName(_fromUtf8("VBoxLayoutLGR"))
        self.mplLGR = MatplotlibWidget(self.tabLGR)
        self.mplLGR.setObjectName(_fromUtf8("mplLGR"))
        self.VBoxLayoutLGR.addWidget(self.mplLGR)
        self.horizontalLayout_3.addLayout(self.VBoxLayoutLGR)
        self.tabWidget.addTab(self.tabLGR, _fromUtf8(""))
        self.tabBode = QtGui.QWidget()
        self.tabBode.setObjectName(_fromUtf8("tabBode"))
        self.tabWidget.addTab(self.tabBode, _fromUtf8(""))
        self.tabNiquist = QtGui.QWidget()
        self.tabNiquist.setObjectName(_fromUtf8("tabNiquist"))
        self.tabWidget.addTab(self.tabNiquist, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuArquivo = QtGui.QMenu(self.menubar)
        self.menuArquivo.setObjectName(_fromUtf8("menuArquivo"))
        self.menuOp_es = QtGui.QMenu(self.menubar)
        self.menuOp_es.setObjectName(_fromUtf8("menuOp_es"))
        self.menuIdioma_Language = QtGui.QMenu(self.menubar)
        self.menuIdioma_Language.setObjectName(_fromUtf8("menuIdioma_Language"))
        self.menuAjuda = QtGui.QMenu(self.menubar)
        self.menuAjuda.setObjectName(_fromUtf8("menuAjuda"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionSalvar_sistema = QtGui.QAction(MainWindow)
        self.actionSalvar_sistema.setObjectName(_fromUtf8("actionSalvar_sistema"))
        self.actionCarregar_sistema = QtGui.QAction(MainWindow)
        self.actionCarregar_sistema.setObjectName(_fromUtf8("actionCarregar_sistema"))
        self.actionResolu_o_da_simula_o = QtGui.QAction(MainWindow)
        self.actionResolu_o_da_simula_o.setObjectName(_fromUtf8("actionResolu_o_da_simula_o"))
        self.actionN_mero_de_pontos_LGR = QtGui.QAction(MainWindow)
        self.actionN_mero_de_pontos_LGR.setObjectName(_fromUtf8("actionN_mero_de_pontos_LGR"))
        self.actionSobre_o_LabControle = QtGui.QAction(MainWindow)
        self.actionSobre_o_LabControle.setObjectName(_fromUtf8("actionSobre_o_LabControle"))
        self.menuArquivo.addAction(self.actionSalvar_sistema)
        self.menuArquivo.addAction(self.actionCarregar_sistema)
        self.menuOp_es.addAction(self.actionResolu_o_da_simula_o)
        self.menuOp_es.addAction(self.actionN_mero_de_pontos_LGR)
        self.menuAjuda.addAction(self.actionSobre_o_LabControle)
        self.menubar.addAction(self.menuArquivo.menuAction())
        self.menubar.addAction(self.menuOp_es.menuAction())
        self.menubar.addAction(self.menuIdioma_Language.menuAction())
        self.menubar.addAction(self.menuAjuda.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "LabControle 2.0", None))
        self.groupBoxRt.setToolTip(_translate("MainWindow", "Parâmetros da entrada de referência", None))
        self.groupBoxRt.setTitle(_translate("MainWindow", "Entrada: r(t)", None))
        self.labelRvalue.setText(_translate("MainWindow", "Valor:", None))
        self.lineEditRvalue.setToolTip(_translate("MainWindow", "Valor do degrau ou função do tempo da entrada", None))
        self.labelRtime.setText(_translate("MainWindow", "Instante:", None))
        self.doubleSpinBoxRtime.setToolTip(_translate("MainWindow", "Instante de tempo em que a entrada será aplicada", None))
        self.groupBoxWt.setToolTip(_translate("MainWindow", "Parâmetros da entrada perturbação", None))
        self.groupBoxWt.setTitle(_translate("MainWindow", "Perturbação: w(t)", None))
        self.labelWvalue.setText(_translate("MainWindow", "Valor:", None))
        self.lineEditWvalue.setToolTip(_translate("MainWindow", "Valor do degrau ou função do tempo da perturbação", None))
        self.labelWtime.setText(_translate("MainWindow", "Instante:", None))
        self.doubleSpinBoxWtime.setToolTip(_translate("MainWindow", "Instante de tempo em que a perturbação será aplicada", None))
        self.comboBoxSys.setToolTip(_translate("MainWindow", "Seleção do tipo de sistema a ser analisado", None))
        self.comboBoxSys.setItemText(0, _translate("MainWindow", "Sistema Linear Contínuo", None))
        self.comboBoxSys.setItemText(1, _translate("MainWindow", "Sistema Linear Discreto (N/A)", None))
        self.comboBoxSys.setItemText(2, _translate("MainWindow", "Sistema não-linear (N/A)", None))
        self.graphicsView.setToolTip(_translate("MainWindow", "Diagrama de blocos do sistema. Use os controles acima para configurar as entradas e abaixo para as funções de transferência", None))
        self.groupBoxMalha.setToolTip(_translate("MainWindow", "Abre/fecha a malha de realimentação", None))
        self.groupBoxMalha.setTitle(_translate("MainWindow", "Malha", None))
        self.radioBtnOpen.setToolTip(_translate("MainWindow", "Abrir a malha de realimentação", None))
        self.radioBtnOpen.setText(_translate("MainWindow", "Aberta", None))
        self.radioBtnClose.setToolTip(_translate("MainWindow", "Fechar a malha de realimentação", None))
        self.radioBtnClose.setText(_translate("MainWindow", "Fechada", None))
        self.groupBoxK.setToolTip(_translate("MainWindow", "Ajuste do ganho de malha direta K", None))
        self.groupBoxK.setTitle(_translate("MainWindow", "Ganho", None))
        self.labelK.setToolTip(_translate("MainWindow", "Ajuste do ganho de malha direta K", None))
        self.doubleSpinBoxK.setToolTip(_translate("MainWindow", "Ajuste do ganho de malha direta K", None))
        self.groupBoxC.setToolTip(_translate("MainWindow", "Habilita/desabilita o controlador", None))
        self.groupBoxC.setTitle(_translate("MainWindow", "Controlador C(s)", None))
        self.labelCnum.setText(_translate("MainWindow", "Num:", None))
        self.lineEditCnum.setToolTip(_translate("MainWindow", "Numerador do controlador C(s)", None))
        self.labelCden.setText(_translate("MainWindow", "Den:", None))
        self.lineEditCden.setToolTip(_translate("MainWindow", "Denominador do controlador C(s)", None))
        self.groupBoxG.setToolTip(_translate("MainWindow", "Habilita/desabilita a planta", None))
        self.groupBoxG.setTitle(_translate("MainWindow", "Planta G(s)", None))
        self.lineEditGnum.setToolTip(_translate("MainWindow", "Numerador da planta G(s)", None))
        self.lineEditGden.setToolTip(_translate("MainWindow", "Denominador da planta G(s)", None))
        self.groupBoxH.setToolTip(_translate("MainWindow", "Habilita/desabilita o sensor", None))
        self.groupBoxH.setTitle(_translate("MainWindow", "Sensor H(s)", None))
        self.labelHnum.setToolTip(_translate("MainWindow", "Denominador do sensor H(s)", None))
        self.lineEditHnum.setToolTip(_translate("MainWindow", "Numerador do sensor H(s)", None))
        self.labelHden.setToolTip(_translate("MainWindow", "Denominador do sensor H(s)", None))
        self.lineEditHden.setToolTip(_translate("MainWindow", "Denominador do sensor H(s)", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDiagrama), _translate("MainWindow", "Diagrama", None))
        self.labelSimulTit.setText(_translate("MainWindow", "Configuração", None))
        self.doubleSpinBoxTmax.setToolTip(_translate("MainWindow", "Entre com o tempo máximo de simulação", None))
        self.labelMostrar.setText(_translate("MainWindow", "Mostrar:", None))
        self.checkBoxSaida.setText(_translate("MainWindow", "Saída: y(t)", None))
        self.checkBoxEntrada.setText(_translate("MainWindow", "Entrada: r(t)", None))
        self.checkBoxErro.setText(_translate("MainWindow", "Erro: e(t)", None))
        self.checkBoxControle.setText(_translate("MainWindow", "Controle: u(t)", None))
        self.checkBoxPert.setText(_translate("MainWindow", "Perturbação: w(t)", None))
        self.btnSimul.setText(_translate("MainWindow", "Simular", None))
        self.btnContinuar.setText(_translate("MainWindow", "Continuar", None))
        self.btnLimparSimul.setText(_translate("MainWindow", "Limpar", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSimul), _translate("MainWindow", "Simulação", None))
        self.labelLGRTit.setText(_translate("MainWindow", "Configuração", None))
        self.doubleSpinBoxKmax.setToolTip(_translate("MainWindow", "Valor máximo de ganho para traçado do LGR", None))
        self.doubleSpinBoxKmin.setToolTip(_translate("MainWindow", "Valor mínimo de ganho para traçado do LGR", None))
        self.doubleSpinBoxKlgr.setToolTip(_translate("MainWindow", "Ajuste do ganho de malha direta K", None))
        self.verticalSliderK.setToolTip(_translate("MainWindow", "Ajuste de ganho de malha direta K", None))
        self.labelRebd.setToolTip(_translate("MainWindow", "Região proibida de tempo de resposta", None))
        self.doubleSpinBoxRebd.setToolTip(_translate("MainWindow", "Valor da restrição de tempo de resposta", None))
        self.labelRibd.setToolTip(_translate("MainWindow", "Região proibida de sobresinal percentual", None))
        self.doubleSpinBoxRibd.setToolTip(_translate("MainWindow", "Valor da restrição de sobressinal percentual", None))
        self.labelImbd.setToolTip(_translate("MainWindow", "Região proibida de tempo de pico", None))
        self.doubleSpinBoxImbd.setToolTip(_translate("MainWindow", "Valor da restrição de tempo de pico", None))
        self.btnPlotLGR.setToolTip(_translate("MainWindow", "Traçar o Lugar Geomátrico das Raízes", None))
        self.btnPlotLGR.setText(_translate("MainWindow", "Traçar LGR", None))
        self.btnPlotLGRcomp.setToolTip(_translate("MainWindow", "Traçar o Lugar Geomátrico das Raízes Complementar", None))
        self.btnPlotLGRcomp.setText(_translate("MainWindow", "Traçar LGR comp.", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabLGR), _translate("MainWindow", "Lugar das Raízes", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabBode), _translate("MainWindow", "Diagrama de Bode", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabNiquist), _translate("MainWindow", "Diagrama de Nyquist", None))
        self.menuArquivo.setTitle(_translate("MainWindow", "Arquivo", None))
        self.menuOp_es.setTitle(_translate("MainWindow", "Opções", None))
        self.menuIdioma_Language.setTitle(_translate("MainWindow", "Idioma/Language", None))
        self.menuAjuda.setTitle(_translate("MainWindow", "Ajuda", None))
        self.actionSalvar_sistema.setText(_translate("MainWindow", "Salvar sistema", None))
        self.actionCarregar_sistema.setText(_translate("MainWindow", "Carregar sistema", None))
        self.actionResolu_o_da_simula_o.setText(_translate("MainWindow", "Resolução da simulação", None))
        self.actionResolu_o_da_simula_o.setToolTip(_translate("MainWindow", "Alterar a resolução da simulação", None))
        self.actionN_mero_de_pontos_LGR.setText(_translate("MainWindow", "Número de pontos LGR", None))
        self.actionN_mero_de_pontos_LGR.setToolTip(_translate("MainWindow", "Alterar o número de pontos do Lugar Geométrico das Raízes", None))
        self.actionSobre_o_LabControle.setText(_translate("MainWindow", "Sobre o LabControle", None))

from matplotlibwidget import MatplotlibWidget

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

