# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created: Wed Apr 09 18:25:33 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setMargin(3)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabDiagrama = QtGui.QWidget()
        self.tabDiagrama.setObjectName(_fromUtf8("tabDiagrama"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tabDiagrama)
        self.verticalLayout_3.setSpacing(1)
        self.verticalLayout_3.setMargin(1)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.frameEntradas = QtGui.QFrame(self.tabDiagrama)
        self.frameEntradas.setMinimumSize(QtCore.QSize(0, 100))
        self.frameEntradas.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameEntradas.setFrameShadow(QtGui.QFrame.Raised)
        self.frameEntradas.setObjectName(_fromUtf8("frameEntradas"))
        self.groupBoxRt = QtGui.QGroupBox(self.frameEntradas)
        self.groupBoxRt.setGeometry(QtCore.QRect(10, 10, 120, 80))
        self.groupBoxRt.setObjectName(_fromUtf8("groupBoxRt"))
        self.groupBoxWt = QtGui.QGroupBox(self.frameEntradas)
        self.groupBoxWt.setGeometry(QtCore.QRect(190, 10, 120, 80))
        self.groupBoxWt.setObjectName(_fromUtf8("groupBoxWt"))
        self.comboBoxSys = QtGui.QComboBox(self.frameEntradas)
        self.comboBoxSys.setGeometry(QtCore.QRect(590, 20, 169, 22))
        self.comboBoxSys.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.comboBoxSys.setObjectName(_fromUtf8("comboBoxSys"))
        self.comboBoxSys.addItem(_fromUtf8(""))
        self.comboBoxSys.addItem(_fromUtf8(""))
        self.verticalLayout_3.addWidget(self.frameEntradas)
        self.graphicsView = QtGui.QGraphicsView(self.tabDiagrama)
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.verticalLayout_3.addWidget(self.graphicsView)
        self.frameSis = QtGui.QFrame(self.tabDiagrama)
        self.frameSis.setMinimumSize(QtCore.QSize(0, 100))
        self.frameSis.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameSis.setFrameShadow(QtGui.QFrame.Raised)
        self.frameSis.setObjectName(_fromUtf8("frameSis"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frameSis)
        self.horizontalLayout.setMargin(1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.groupBoxMalha = QtGui.QGroupBox(self.frameSis)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBoxMalha.setFont(font)
        self.groupBoxMalha.setObjectName(_fromUtf8("groupBoxMalha"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBoxMalha)
        self.verticalLayout_4.setContentsMargins(4, 2, 4, 4)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.radioBtnOpen = QtGui.QRadioButton(self.groupBoxMalha)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioBtnOpen.setFont(font)
        self.radioBtnOpen.setChecked(True)
        self.radioBtnOpen.setAutoExclusive(True)
        self.radioBtnOpen.setObjectName(_fromUtf8("radioBtnOpen"))
        self.verticalLayout_4.addWidget(self.radioBtnOpen)
        self.radioBtnClose = QtGui.QRadioButton(self.groupBoxMalha)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioBtnClose.setFont(font)
        self.radioBtnClose.setObjectName(_fromUtf8("radioBtnClose"))
        self.verticalLayout_4.addWidget(self.radioBtnClose)
        self.horizontalLayout.addWidget(self.groupBoxMalha)
        self.groupBoxK = QtGui.QGroupBox(self.frameSis)
        self.groupBoxK.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBoxK.setFont(font)
        self.groupBoxK.setStyleSheet(_fromUtf8("QGroupBox {border-width: 2px; border-style: solid;\n"
"border-color: rgb(255, 170, 170);\n"
"border-radius: 5px;}\n"
"QGroupBox::title {\n"
"     background-color: transparent;\n"
"     subcontrol-origin: border;\n"
"     subcontrol-position: top left; /* position at the top center */\n"
"     padding: 0 10px;\n"
" }"))
        self.groupBoxK.setObjectName(_fromUtf8("groupBoxK"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBoxK)
        self.verticalLayout_5.setContentsMargins(1, 4, 1, 4)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.labelK = QtGui.QLabel(self.groupBoxK)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelK.sizePolicy().hasHeightForWidth())
        self.labelK.setSizePolicy(sizePolicy)
        self.labelK.setMinimumSize(QtCore.QSize(0, 20))
        self.labelK.setMaximumSize(QtCore.QSize(200, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelK.setFont(font)
        self.labelK.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelK.setText(_fromUtf8("K:"))
        self.labelK.setAlignment(QtCore.Qt.AlignCenter)
        self.labelK.setObjectName(_fromUtf8("labelK"))
        self.verticalLayout_5.addWidget(self.labelK)
        self.doubleSpinBox = QtGui.QDoubleSpinBox(self.groupBoxK)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox.setSizePolicy(sizePolicy)
        self.doubleSpinBox.setMinimumSize(QtCore.QSize(0, 25))
        self.doubleSpinBox.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.doubleSpinBox.setFont(font)
        self.doubleSpinBox.setMinimum(-200.0)
        self.doubleSpinBox.setMaximum(200.0)
        self.doubleSpinBox.setProperty("value", 1.0)
        self.doubleSpinBox.setObjectName(_fromUtf8("doubleSpinBox"))
        self.verticalLayout_5.addWidget(self.doubleSpinBox)
        self.horizontalLayout.addWidget(self.groupBoxK)
        self.groupBoxC = QtGui.QGroupBox(self.frameSis)
        self.groupBoxC.setEnabled(True)
        self.groupBoxC.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBoxC.setFont(font)
        self.groupBoxC.setStyleSheet(_fromUtf8("QGroupBox {border-width: 2px; border-style: solid;\n"
"border-color: rgb(175, 198, 233);\n"
"border-radius: 5px;}\n"
"QGroupBox::title {\n"
"     background-color: transparent;\n"
"     subcontrol-origin: border;\n"
"     subcontrol-position: top left; /* position at the top center */\n"
"     padding: 0 10px;\n"
" }"))
        self.groupBoxC.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBoxC.setCheckable(True)
        self.groupBoxC.setChecked(False)
        self.groupBoxC.setObjectName(_fromUtf8("groupBoxC"))
        self.gridLayout = QtGui.QGridLayout(self.groupBoxC)
        self.gridLayout.setContentsMargins(4, 4, 4, 0)
        self.gridLayout.setVerticalSpacing(1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.labelCnum = QtGui.QLabel(self.groupBoxC)
        self.labelCnum.setMinimumSize(QtCore.QSize(40, 0))
        self.labelCnum.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelCnum.setFont(font)
        self.labelCnum.setObjectName(_fromUtf8("labelCnum"))
        self.gridLayout.addWidget(self.labelCnum, 0, 0, 1, 1)
        self.lineEditCnum = QtGui.QLineEdit(self.groupBoxC)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditCnum.sizePolicy().hasHeightForWidth())
        self.lineEditCnum.setSizePolicy(sizePolicy)
        self.lineEditCnum.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEditCnum.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditCnum.setFont(font)
        self.lineEditCnum.setText(_fromUtf8("1"))
        self.lineEditCnum.setObjectName(_fromUtf8("lineEditCnum"))
        self.gridLayout.addWidget(self.lineEditCnum, 0, 1, 1, 1)
        self.labelCden = QtGui.QLabel(self.groupBoxC)
        self.labelCden.setMinimumSize(QtCore.QSize(40, 0))
        self.labelCden.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelCden.setFont(font)
        self.labelCden.setObjectName(_fromUtf8("labelCden"))
        self.gridLayout.addWidget(self.labelCden, 1, 0, 1, 1)
        self.lineEditCden = QtGui.QLineEdit(self.groupBoxC)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditCden.sizePolicy().hasHeightForWidth())
        self.lineEditCden.setSizePolicy(sizePolicy)
        self.lineEditCden.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEditCden.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditCden.setFont(font)
        self.lineEditCden.setText(_fromUtf8("1"))
        self.lineEditCden.setObjectName(_fromUtf8("lineEditCden"))
        self.gridLayout.addWidget(self.lineEditCden, 1, 1, 1, 1)
        self.horizontalLayout.addWidget(self.groupBoxC)
        self.groupBoxG = QtGui.QGroupBox(self.frameSis)
        self.groupBoxG.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBoxG.setFont(font)
        self.groupBoxG.setStyleSheet(_fromUtf8("QGroupBox {border-width: 2px; border-style: solid;\n"
"border-color: rgb(95, 211, 141);\n"
"border-radius: 5px;}\n"
"QGroupBox::title {\n"
"     background-color: transparent;\n"
"     subcontrol-origin: border;\n"
"     subcontrol-position: top left; /* position at the top center */\n"
"     padding: 0 10px;\n"
" }"))
        self.groupBoxG.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBoxG.setCheckable(True)
        self.groupBoxG.setObjectName(_fromUtf8("groupBoxG"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBoxG)
        self.gridLayout_2.setContentsMargins(4, 4, 4, 0)
        self.gridLayout_2.setVerticalSpacing(1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.labelGnum = QtGui.QLabel(self.groupBoxG)
        self.labelGnum.setMinimumSize(QtCore.QSize(40, 0))
        self.labelGnum.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelGnum.setFont(font)
        self.labelGnum.setText(_fromUtf8("Num:"))
        self.labelGnum.setObjectName(_fromUtf8("labelGnum"))
        self.gridLayout_2.addWidget(self.labelGnum, 0, 0, 1, 1)
        self.lineEditGnum = QtGui.QLineEdit(self.groupBoxG)
        self.lineEditGnum.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEditGnum.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditGnum.setFont(font)
        self.lineEditGnum.setText(_fromUtf8("1"))
        self.lineEditGnum.setObjectName(_fromUtf8("lineEditGnum"))
        self.gridLayout_2.addWidget(self.lineEditGnum, 0, 1, 1, 1)
        self.labelGden = QtGui.QLabel(self.groupBoxG)
        self.labelGden.setMinimumSize(QtCore.QSize(40, 0))
        self.labelGden.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelGden.setFont(font)
        self.labelGden.setText(_fromUtf8("Den:"))
        self.labelGden.setObjectName(_fromUtf8("labelGden"))
        self.gridLayout_2.addWidget(self.labelGden, 1, 0, 1, 1)
        self.lineEditGden = QtGui.QLineEdit(self.groupBoxG)
        self.lineEditGden.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEditGden.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditGden.setFont(font)
        self.lineEditGden.setText(_fromUtf8("1"))
        self.lineEditGden.setObjectName(_fromUtf8("lineEditGden"))
        self.gridLayout_2.addWidget(self.lineEditGden, 1, 1, 1, 1)
        self.horizontalLayout.addWidget(self.groupBoxG)
        self.groupBoxH = QtGui.QGroupBox(self.frameSis)
        self.groupBoxH.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBoxH.setFont(font)
        self.groupBoxH.setStyleSheet(_fromUtf8("QGroupBox {border-width: 2px; border-style: solid;\n"
"border-color: rgb(255, 246, 136);\n"
"border-radius: 5px;}\n"
"QGroupBox::title {\n"
"     background-color: transparent;\n"
"     subcontrol-origin: border;\n"
"     subcontrol-position: top left; /* position at the top center */\n"
"     padding: 0 10px;\n"
" }"))
        self.groupBoxH.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBoxH.setCheckable(True)
        self.groupBoxH.setChecked(False)
        self.groupBoxH.setObjectName(_fromUtf8("groupBoxH"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBoxH)
        self.gridLayout_3.setContentsMargins(4, 4, 4, 0)
        self.gridLayout_3.setVerticalSpacing(1)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.labelHnum = QtGui.QLabel(self.groupBoxH)
        self.labelHnum.setMinimumSize(QtCore.QSize(40, 0))
        self.labelHnum.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelHnum.setFont(font)
        self.labelHnum.setText(_fromUtf8("Num:"))
        self.labelHnum.setObjectName(_fromUtf8("labelHnum"))
        self.gridLayout_3.addWidget(self.labelHnum, 0, 0, 1, 1)
        self.lineEditHnum = QtGui.QLineEdit(self.groupBoxH)
        self.lineEditHnum.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEditHnum.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditHnum.setFont(font)
        self.lineEditHnum.setText(_fromUtf8("1"))
        self.lineEditHnum.setObjectName(_fromUtf8("lineEditHnum"))
        self.gridLayout_3.addWidget(self.lineEditHnum, 0, 1, 1, 1)
        self.labelHden = QtGui.QLabel(self.groupBoxH)
        self.labelHden.setMinimumSize(QtCore.QSize(40, 0))
        self.labelHden.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelHden.setFont(font)
        self.labelHden.setText(_fromUtf8("Den:"))
        self.labelHden.setObjectName(_fromUtf8("labelHden"))
        self.gridLayout_3.addWidget(self.labelHden, 1, 0, 1, 1)
        self.lineEditHden = QtGui.QLineEdit(self.groupBoxH)
        self.lineEditHden.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEditHden.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditHden.setFont(font)
        self.lineEditHden.setText(_fromUtf8("1"))
        self.lineEditHden.setObjectName(_fromUtf8("lineEditHden"))
        self.gridLayout_3.addWidget(self.lineEditHden, 1, 1, 1, 1)
        self.horizontalLayout.addWidget(self.groupBoxH)
        self.verticalLayout_3.addWidget(self.frameSis)
        self.tabWidget.addTab(self.tabDiagrama, _fromUtf8(""))
        self.tabSimul = QtGui.QWidget()
        self.tabSimul.setObjectName(_fromUtf8("tabSimul"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tabSimul)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.frameSimul = QtGui.QFrame(self.tabSimul)
        self.frameSimul.setMinimumSize(QtCore.QSize(120, 0))
        self.frameSimul.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frameSimul.setAutoFillBackground(False)
        self.frameSimul.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameSimul.setFrameShadow(QtGui.QFrame.Raised)
        self.frameSimul.setLineWidth(1)
        self.frameSimul.setObjectName(_fromUtf8("frameSimul"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frameSimul)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.labelSimulTit = QtGui.QLabel(self.frameSimul)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelSimulTit.setFont(font)
        self.labelSimulTit.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSimulTit.setObjectName(_fromUtf8("labelSimulTit"))
        self.verticalLayout_2.addWidget(self.labelSimulTit)
        self.labelTmax = QtGui.QLabel(self.frameSimul)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelTmax.setFont(font)
        self.labelTmax.setText(_fromUtf8("Tmax [s]:"))
        self.labelTmax.setObjectName(_fromUtf8("labelTmax"))
        self.verticalLayout_2.addWidget(self.labelTmax)
        self.lineEditTmax = QtGui.QLineEdit(self.frameSimul)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditTmax.setFont(font)
        self.lineEditTmax.setInputMask(_fromUtf8(""))
        self.lineEditTmax.setText(_fromUtf8("10"))
        self.lineEditTmax.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditTmax.setPlaceholderText(_fromUtf8(""))
        self.lineEditTmax.setObjectName(_fromUtf8("lineEditTmax"))
        self.verticalLayout_2.addWidget(self.lineEditTmax)
        spacerItem = QtGui.QSpacerItem(20, 60, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.labelMostrar = QtGui.QLabel(self.frameSimul)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelMostrar.setFont(font)
        self.labelMostrar.setObjectName(_fromUtf8("labelMostrar"))
        self.verticalLayout_2.addWidget(self.labelMostrar)
        self.checkBoxSaida = QtGui.QCheckBox(self.frameSimul)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.checkBoxSaida.setFont(font)
        self.checkBoxSaida.setChecked(True)
        self.checkBoxSaida.setObjectName(_fromUtf8("checkBoxSaida"))
        self.verticalLayout_2.addWidget(self.checkBoxSaida)
        self.checkBoxEntrada = QtGui.QCheckBox(self.frameSimul)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBoxEntrada.setFont(font)
        self.checkBoxEntrada.setChecked(True)
        self.checkBoxEntrada.setObjectName(_fromUtf8("checkBoxEntrada"))
        self.verticalLayout_2.addWidget(self.checkBoxEntrada)
        self.checkBoxErro = QtGui.QCheckBox(self.frameSimul)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBoxErro.setFont(font)
        self.checkBoxErro.setObjectName(_fromUtf8("checkBoxErro"))
        self.verticalLayout_2.addWidget(self.checkBoxErro)
        self.checkBoxControle = QtGui.QCheckBox(self.frameSimul)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBoxControle.setFont(font)
        self.checkBoxControle.setObjectName(_fromUtf8("checkBoxControle"))
        self.verticalLayout_2.addWidget(self.checkBoxControle)
        self.checkBoxPert = QtGui.QCheckBox(self.frameSimul)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBoxPert.setFont(font)
        self.checkBoxPert.setObjectName(_fromUtf8("checkBoxPert"))
        self.verticalLayout_2.addWidget(self.checkBoxPert)
        spacerItem1 = QtGui.QSpacerItem(20, 61, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.btnPlot = QtGui.QPushButton(self.frameSimul)
        self.btnPlot.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnPlot.setFont(font)
        self.btnPlot.setObjectName(_fromUtf8("btnPlot"))
        self.verticalLayout_2.addWidget(self.btnPlot)
        self.btnContinuar = QtGui.QPushButton(self.frameSimul)
        self.btnContinuar.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnContinuar.setFont(font)
        self.btnContinuar.setObjectName(_fromUtf8("btnContinuar"))
        self.verticalLayout_2.addWidget(self.btnContinuar)
        self.btnLimparSimul = QtGui.QPushButton(self.frameSimul)
        self.btnLimparSimul.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnLimparSimul.setFont(font)
        self.btnLimparSimul.setObjectName(_fromUtf8("btnLimparSimul"))
        self.verticalLayout_2.addWidget(self.btnLimparSimul)
        self.horizontalLayout_2.addWidget(self.frameSimul)
        self.VBoxLayoutSimul = QtGui.QVBoxLayout()
        self.VBoxLayoutSimul.setObjectName(_fromUtf8("VBoxLayoutSimul"))
        self.mplSimul = MatplotlibWidget(self.tabSimul)
        self.mplSimul.setObjectName(_fromUtf8("mplSimul"))
        self.VBoxLayoutSimul.addWidget(self.mplSimul)
        self.horizontalLayout_2.addLayout(self.VBoxLayoutSimul)
        self.tabWidget.addTab(self.tabSimul, _fromUtf8(""))
        self.tabLGR = QtGui.QWidget()
        self.tabLGR.setObjectName(_fromUtf8("tabLGR"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.tabLGR)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.tabWidget.addTab(self.tabLGR, _fromUtf8(""))
        self.tabBode = QtGui.QWidget()
        self.tabBode.setObjectName(_fromUtf8("tabBode"))
        self.tabWidget.addTab(self.tabBode, _fromUtf8(""))
        self.tabNiquist = QtGui.QWidget()
        self.tabNiquist.setObjectName(_fromUtf8("tabNiquist"))
        self.tabWidget.addTab(self.tabNiquist, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuArquivo = QtGui.QMenu(self.menubar)
        self.menuArquivo.setObjectName(_fromUtf8("menuArquivo"))
        self.menuOp_es = QtGui.QMenu(self.menubar)
        self.menuOp_es.setObjectName(_fromUtf8("menuOp_es"))
        self.menuIdioma_Language = QtGui.QMenu(self.menubar)
        self.menuIdioma_Language.setObjectName(_fromUtf8("menuIdioma_Language"))
        self.menuAjuda = QtGui.QMenu(self.menubar)
        self.menuAjuda.setObjectName(_fromUtf8("menuAjuda"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionSalvar_sistema = QtGui.QAction(MainWindow)
        self.actionSalvar_sistema.setObjectName(_fromUtf8("actionSalvar_sistema"))
        self.actionCarregar_sistema = QtGui.QAction(MainWindow)
        self.actionCarregar_sistema.setObjectName(_fromUtf8("actionCarregar_sistema"))
        self.actionResolu_o_da_simula_o = QtGui.QAction(MainWindow)
        self.actionResolu_o_da_simula_o.setObjectName(_fromUtf8("actionResolu_o_da_simula_o"))
        self.actionN_mero_de_pontos_LGR = QtGui.QAction(MainWindow)
        self.actionN_mero_de_pontos_LGR.setObjectName(_fromUtf8("actionN_mero_de_pontos_LGR"))
        self.actionSobre_o_LabControle = QtGui.QAction(MainWindow)
        self.actionSobre_o_LabControle.setObjectName(_fromUtf8("actionSobre_o_LabControle"))
        self.menuArquivo.addAction(self.actionSalvar_sistema)
        self.menuArquivo.addAction(self.actionCarregar_sistema)
        self.menuOp_es.addAction(self.actionResolu_o_da_simula_o)
        self.menuOp_es.addAction(self.actionN_mero_de_pontos_LGR)
        self.menuAjuda.addAction(self.actionSobre_o_LabControle)
        self.menubar.addAction(self.menuArquivo.menuAction())
        self.menubar.addAction(self.menuOp_es.menuAction())
        self.menubar.addAction(self.menuIdioma_Language.menuAction())
        self.menubar.addAction(self.menuAjuda.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "LabControle 2.0", None))
        self.groupBoxRt.setTitle(_translate("MainWindow", "Entrada: r(t)", None))
        self.groupBoxWt.setTitle(_translate("MainWindow", "Perturbação: w(t)", None))
        self.comboBoxSys.setToolTip(_translate("MainWindow", "Seleção do tipo de sistema a ser analisado", None))
        self.comboBoxSys.setItemText(0, _translate("MainWindow", "Sistema Linear", None))
        self.comboBoxSys.setItemText(1, _translate("MainWindow", "Sistema não-linear (N/A)", None))
        self.graphicsView.setToolTip(_translate("MainWindow", "Diagrama de blocos do sistema. Use os controles acima para configurar as entradas e abaixo para as funções de transferência", None))
        self.groupBoxMalha.setToolTip(_translate("MainWindow", "Abre/fecha a malha de realimentação", None))
        self.groupBoxMalha.setTitle(_translate("MainWindow", "Malha", None))
        self.radioBtnOpen.setToolTip(_translate("MainWindow", "Abrir a malha de realimentação", None))
        self.radioBtnOpen.setText(_translate("MainWindow", "Aberta", None))
        self.radioBtnClose.setToolTip(_translate("MainWindow", "Fechar a malha de realimentação", None))
        self.radioBtnClose.setText(_translate("MainWindow", "Fechada", None))
        self.groupBoxK.setToolTip(_translate("MainWindow", "Ajuste do ganho de malha direta K", None))
        self.groupBoxK.setTitle(_translate("MainWindow", "Ganho", None))
        self.labelK.setToolTip(_translate("MainWindow", "Ajuste do ganho de malha direta K", None))
        self.doubleSpinBox.setToolTip(_translate("MainWindow", "Ajuste do ganho de malha direta K", None))
        self.groupBoxC.setToolTip(_translate("MainWindow", "Habilita/desabilita o controlador", None))
        self.groupBoxC.setTitle(_translate("MainWindow", "Controlador C(s)", None))
        self.labelCnum.setText(_translate("MainWindow", "Num:", None))
        self.lineEditCnum.setToolTip(_translate("MainWindow", "Numerador do controlador C(s)", None))
        self.labelCden.setText(_translate("MainWindow", "Den:", None))
        self.lineEditCden.setToolTip(_translate("MainWindow", "Denominador do controlador C(s)", None))
        self.groupBoxG.setToolTip(_translate("MainWindow", "Habilita/desabilita a planta", None))
        self.groupBoxG.setTitle(_translate("MainWindow", "Planta G(s)", None))
        self.lineEditGnum.setToolTip(_translate("MainWindow", "Numerador da planta G(s)", None))
        self.lineEditGden.setToolTip(_translate("MainWindow", "Denominador da planta G(s)", None))
        self.groupBoxH.setToolTip(_translate("MainWindow", "Habilita/desabilita o sensor", None))
        self.groupBoxH.setTitle(_translate("MainWindow", "Sensor H(s)", None))
        self.labelHnum.setToolTip(_translate("MainWindow", "Denominador do sensor H(s)", None))
        self.lineEditHnum.setToolTip(_translate("MainWindow", "Numerador do sensor H(s)", None))
        self.labelHden.setToolTip(_translate("MainWindow", "Denominador do sensor H(s)", None))
        self.lineEditHden.setToolTip(_translate("MainWindow", "Denominador do sensor H(s)", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDiagrama), _translate("MainWindow", "Diagrama", None))
        self.labelSimulTit.setText(_translate("MainWindow", "Configuração", None))
        self.lineEditTmax.setToolTip(_translate("MainWindow", "Tempo máximo de simulação", None))
        self.labelMostrar.setText(_translate("MainWindow", "Mostrar:", None))
        self.checkBoxSaida.setText(_translate("MainWindow", "Saída: y(t)", None))
        self.checkBoxEntrada.setText(_translate("MainWindow", "Entrada: r(t)", None))
        self.checkBoxErro.setText(_translate("MainWindow", "Erro: e(t)", None))
        self.checkBoxControle.setText(_translate("MainWindow", "Controle: u(t)", None))
        self.checkBoxPert.setText(_translate("MainWindow", "Perturbação: w(t)", None))
        self.btnPlot.setText(_translate("MainWindow", "Plot", None))
        self.btnContinuar.setText(_translate("MainWindow", "Continuar", None))
        self.btnLimparSimul.setText(_translate("MainWindow", "Limpar", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSimul), _translate("MainWindow", "Simulação", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabLGR), _translate("MainWindow", "Lugar das Raízes", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabBode), _translate("MainWindow", "Diagrama de Bode", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabNiquist), _translate("MainWindow", "Diagrama de Nyquist", None))
        self.menuArquivo.setTitle(_translate("MainWindow", "Arquivo", None))
        self.menuOp_es.setTitle(_translate("MainWindow", "Opções", None))
        self.menuIdioma_Language.setTitle(_translate("MainWindow", "Idioma/Language", None))
        self.menuAjuda.setTitle(_translate("MainWindow", "Ajuda", None))
        self.actionSalvar_sistema.setText(_translate("MainWindow", "Salvar sistema", None))
        self.actionCarregar_sistema.setText(_translate("MainWindow", "Carregar sistema", None))
        self.actionResolu_o_da_simula_o.setText(_translate("MainWindow", "Resolução da simulação", None))
        self.actionResolu_o_da_simula_o.setToolTip(_translate("MainWindow", "Alterar a resolução da simulação", None))
        self.actionN_mero_de_pontos_LGR.setText(_translate("MainWindow", "Número de pontos LGR", None))
        self.actionN_mero_de_pontos_LGR.setToolTip(_translate("MainWindow", "Alterar o número de pontos do Lugar Geométrico das Raízes", None))
        self.actionSobre_o_LabControle.setText(_translate("MainWindow", "Sobre o LabControle", None))

from matplotlibwidget import MatplotlibWidget

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

